services:
  auth-server:
    container_name: auth-server
    hostname: auth
    volumes:
      - ./api-keys:/etc/api-keys
    build:
      dockerfile: ./auth-server/Dockerfile
    networks:
      - app-network

  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    hostname: ollama
    build:
      dockerfile: ./ollama-server/Dockerfile
    volumes:
      - ./ollama-server/entrypoint.sh:/entrypoint.sh
    networks:
      - app-network
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

  caddy-server:
    image: caddy:2.9.1
    container_name: caddy-server
    restart: unless-stopped
    hostname: caddy
    depends_on:
      - auth-server
      - ollama-server
    build:
      dockerfile: ./caddy-server/Dockerfile
    ports:
      - "9000:9000"
    networks:
      - app-network
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

networks:
  app-network:
    driver: bridge
