services:
  auth-server:
    container_name: auth-server
    hostname: auth
    volumes:
      - ./api-keys:/etc/api-keys
    build:
      dockerfile: ./auth-server/Dockerfile
    networks:
      - app-network

  caddy-server:
    image: caddy:2.9.1
    container_name: caddy-server
    restart: unless-stopped
    hostname: caddy
    depends_on:
      - auth-server
    build:
      dockerfile: ./caddy-server/Dockerfile
    ports:
      - "9000:9000"
    networks:
      - app-network
    volumes:
      - ./caddy/macnative/Caddyfile:/etc/caddy/Caddyfile
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge
